//! Opening book: `book.txt` (generated by `arena/book.py` with full-strength Stockfish) is embedded
//! at compile time. Lines are `<epd> <uci move>`; only white-to-move positions are stored.

use shakmaty::fen::Epd;
use shakmaty::uci::UciMove;
use shakmaty::{Chess, EnPassantMode, Move};

const BOOK: &str = include_str!("../book.txt");

/// Book move for `pos`, if any (verified to be legal).
pub fn probe(pos: &Chess) -> Option<Move> {
    let epd = Epd::from_position(pos.clone(), EnPassantMode::Legal).to_string();
    let uci = BOOK
        .lines()
        .find_map(|line| line.strip_prefix(epd.as_str()).and_then(|rest| rest.strip_prefix(' ')))?;
    uci.trim().parse::<UciMove>().ok()?.to_move(pos).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use shakmaty::fen::Fen;
    use shakmaty::CastlingMode;

    #[test]
    fn startpos_is_in_book() {
        assert!(probe(&Chess::default()).is_some());
    }

    #[test]
    fn book_moves_are_legal_and_follow_the_line() {
        // play the book's own line from the start; every white move must come from the book
        let mut pos = Chess::default();
        let first = probe(&pos).unwrap();
        pos.play_unchecked(&first);
        let reply = pos.legal_moves().into_iter().next().unwrap();
        pos.play_unchecked(&reply);
        // a reply the book may not cover: probe must return None or a legal move, never panic
        if let Some(m) = probe(&pos) {
            assert!(pos.is_legal(&m));
        }
    }

    #[test]
    fn unknown_position_is_not_in_book() {
        let pos: Chess = "8/8/8/8/8/4k3/8/Q3K3 w - - 0 1"
            .parse::<Fen>()
            .unwrap()
            .into_position(CastlingMode::Standard)
            .unwrap();
        assert!(probe(&pos).is_none());
    }
}
